"""Render run results: rich terminal matrix and GitHub-flavored markdown."""

from rich import box
from rich.console import Console
from rich.table import Table

from .runner import RunResult

console = Console()


def render_terminal(run: RunResult, verbose: bool = False) -> None:
    """Print the pass/fail matrix and any failure details."""
    console.print()
    console.rule("[bold cyan] promptdiff [/bold cyan]")
    console.print(f"[dim]  provider: {run.suite_provider}   model: {run.model}[/dim]\n")

    tbl = Table(box=box.ROUNDED, border_style="cyan", header_style="bold cyan")
    tbl.add_column("Case", style="bold", min_width=20)
    for v in run.versions:
        tbl.add_column(v, justify="center", min_width=10)

    case_names = []
    for r in run.results:
        if r.case not in case_names:
            case_names.append(r.case)

    by = {(r.case, r.version): r for r in run.results}
    for name in case_names:
        row = [name]
        for v in run.versions:
            r = by.get((name, v))
            if r is None:
                row.append("[dim]-[/dim]")
            elif r.error:
                row.append("[red]ERROR[/red]")
            elif r.passed:
                row.append("[green]PASS[/green]" + (" [dim]*[/dim]" if r.cached else ""))
            else:
                row.append("[red]FAIL[/red]" + (" [dim]*[/dim]" if r.cached else ""))
        tbl.add_row(*row)

    console.print(tbl)
    console.print("[dim]  * = served from cache[/dim]\n")

    # Failure details
    failures = [r for r in run.results if not r.passed]
    for r in failures:
        console.print(f"[red]x[/red] [bold]{r.case}[/bold] @ {r.version}")
        if r.error:
            console.print(f"  [red]provider error:[/red] {r.error}")
        for c in r.checks:
            if not c.passed:
                console.print(f"  [yellow]{c.type}[/yellow]: {c.detail}")
        if verbose and r.output:
            console.print(f"  [dim]output: {r.output[:200]}[/dim]")
        console.print()

    # Regressions
    regs = run.regressions()
    if regs:
        console.print(
            f"[bold red]REGRESSION:[/bold red] {len(regs)} case(s) pass in "
            f"'{run.versions[0]}' but fail in a later version: {', '.join(regs)}\n"
        )

    total = len(run.results)
    passed = total - run.failed
    color = "green" if run.failed == 0 else "red"
    console.rule(f"[{color}] {passed}/{total} passed [/{color}]")
    console.print()


def to_markdown(run: RunResult) -> str:
    """GitHub-flavored markdown report for PR comments."""
    regs = run.regressions()
    total = len(run.results)
    passed = total - run.failed
    status = "🟢" if run.failed == 0 else ("🔴" if regs else "🟡")

    lines = [
        f"## {status} promptdiff — {passed}/{total} checks passed",
        "",
        f"Provider: `{run.suite_provider}` · Model: `{run.model}`",
        "",
        "| Case | " + " | ".join(run.versions) + " |",
        "|---|" + "---|" * len(run.versions),
    ]

    case_names = []
    for r in run.results:
        if r.case not in case_names:
            case_names.append(r.case)
    by = {(r.case, r.version): r for r in run.results}

    for name in case_names:
        cells = []
        for v in run.versions:
            r = by.get((name, v))
            cells.append("✅" if (r and r.passed) else "❌")
        lines.append(f"| {name} | " + " | ".join(cells) + " |")

    if regs:
        lines += ["", f"**⚠️ Regression:** `{'`, `'.join(regs)}` pass in "
                      f"`{run.versions[0]}` but fail in a later version."]

    failures = [r for r in run.results if not r.passed]
    if failures:
        lines += ["", "<details><summary>Failure details</summary>", ""]
        for r in failures:
            lines.append(f"- **{r.case}** @ `{r.version}`")
            if r.error:
                lines.append(f"  - provider error: `{r.error[:150]}`")
            for c in r.checks:
                if not c.passed:
                    lines.append(f"  - `{c.type}`: {c.detail}")
        lines += ["", "</details>"]

    lines += ["", "*Generated by [promptdiff](https://github.com/FaZ07/promptdiff) — "
                  "regression testing for LLM prompts.*"]
    return "\n".join(lines)
